apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env: 
        - name: DB_URL
          valueFrom:
           configMapKeyRef:
            name: mongo-config
            key: mongo-url
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
           
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  webapp-service
  namespace: madapi-preprod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        -  webapp-service.falugtestaks.eastus2.cloudapp.azure.com
  rules:
    - host:  webapp-service.falugtestaks.eastus2.cloudapp.azure.com
      http:
        paths:
        - backend:
            service:
              name: webapp-service
              port:
                number: 3000
          path: /
          pathType: Prefix
